version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongomp
    ports:
      - 27017:27017
    volumes:
      - missingpetsdbdata:/data/db

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmqmp
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - mprabbitmqdata:/var/lib/rabbitmq
    hostname: rabbitmq

volumes:
  missingpetsdbdata:
  mprabbitmqdata:
